version: "3"
services:
  acme-services:
    build:
      context: ./
      dockerfile: Dockerfile
    image: acme-service/node:1.0
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    restart: always
    container_name: acme-services
    volumes:
      - ./src:/home/node/app/src
    expose:
      - "5000"
    ports:
      - "5001:5000"
    command: "npm start"